AWSTemplateFormatVersion: 2010-09-09
Description: Cloudformation to enable AWS GuardDuty Detector
Resources:
  GuardDuty:
    Type: AWS::GuardDuty::Detector
    Properties:
      Enable: true
      FindingPublishingFrequency: SIX_HOURS
      DataSources:
        S3Logs:
          Enable: true
